# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - github-bitso

jobs:
  build:
    docker:
      # specify the version you desire here jdk 16?
      - image: cimg/openjdk:16.0.2-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - install-java
      # Download and cache dependencies
      - restore_cache:
          keys:
            # FIXME: Replace the () with double {} once the template is created
            - v1-dependencies-( checksum "build.gradle" )
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          # FIXME: Replace the () with double {} once the template is created
          key: v1-dependencies-( checksum "build.gradle" )

      # run tests!
      - run: gradle test

      - store_test_results:
          path: app/build/test-results
