name: Bitso Pull Request Integrator
on:
  issue_comment:
    types: [created]
jobs:
  command_dispatcher:
    name: CI Bot Command Dispatcher
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Integrator Repo
        uses: actions/checkout@v2
        with:
          repository: bitsoex/bort
          ref: master
          token: ${{ secrets.BOT_TOKEN }}
          path: ./.github/actions/bort  
      - name: Dispatch Command   
        uses: ./.github/actions/bort/integrator-action
        id: integrate-branches
        env:
          API_KEY: '${{ secrets.API_KEY }}'
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          integration-branch: 'staging'
          main-branch: 'master'
          target-label: 'stage-ready'
