name: terraform format

on:
  pull_request:
    paths:
    - '**.tf'

# FIXME: Add interpolation symbols to GitHub context expressions after generating the templates.
# https://docs.github.com/en/actions/learn-github-actions/expressions
env:
  PULL_REQUEST: github.event.pull_request.number
  TOKEN: secrets.GITHUB_TOKEN
  GITHUB_REPOSITORY: github.event.repository.name
jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 1.0.0

      - name: Run fmt on affected tf folders
        run: |
          URL="https://api.github.com/repos/bitsoex/$GITHUB_REPOSITORY/pulls/$PULL_REQUEST/files"
          FILES=$(curl -s -X GET  \
          --header 'Authorization: Bearer $TOKEN' \
          -G $URL  | jq -r '.[] | .filename' | grep '.\tf$' | sed 's:[^/]*$::')
          for file in $FILES;
          do
            echo $file
            pushd $file
            terraform fmt -check -recursive 
            popd
          done
