# Deployment resource values
deployment:
  applicationName: default
  image:
    imageName: default
  dnsmasq:
    enabled: false
  annotations:
    sidecar.istio.io/inject: "true"
  args:
    - /general-scripts/run_java.sh
  env:
    fromConfigmap:
      default:
        VARIABLE_NAME: variable_name
        ENVIRONMENT: environment
      general-config:
        MANAGEMENT_METRICS_EXPORT_STATSD_PORT: dogstatsd_port
        SLACK_ENV: slack_env
    fromFieldRef:
      MANAGEMENT_METRICS_EXPORT_STATSD_HOST: status.hostIP

  ports:
    - name: proto
      containerPort: 8000
      protocol: TCP
  livenessProbe:
    exec:
      command:
      - /app/liveness
      - localhost:8000
    periodSeconds: 3
    initialDelaySeconds: 40
  readinessProbe:
    exec:
      command:
      - /app/liveness
      - localhost:8000
    periodSeconds: 3
    initialDelaySeconds: 40
  lifecycle:
    preStop:
      exec:
        command:
          - /app/prestop.sh
  volumes:
    configMaps:
      - name: general-scripts
        mapname: general-scripts
        mountPath: /general-scripts
        defaultMode: 365

# Service resource values
service:
  enabled: true
  clusterIP:
    ports:
      - name: proto
        protocol: TCP
        targetPort: proto
        port: 8000

# ConfigMap resource values
configmap:
  enabled: true
  data:
    variable_name: variable_value

# Peer authentication policy to act as an exception to mTLS in the proto port.
peerAuthn:
  enabled: true
  spec:
    selector:
      matchLabels:
        app: default
    mtls:
      mode: STRICT
    portLevelMtls:
      8000:
        mode: PERMISSIVE
