# Deployment resource values
deployment:
  replicaCount: 2
  envMemory: true
  resources:
    requests:
      cpu: 500m
      memory: 255Mi
    limits:
      cpu: 750m
      memory: 512Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1


# ConfigMap resource values
configmap:
  data:
    environment: prod 

#Add destination rule to allow mTLS exception
destinationrule:
  enabled: true
  spec:
    host: default.prod.svc.cluster.local
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
      portLevelSettings:
      - port:
          number: 8000
        tls:
          mode: DISABLE
